server:
  port: 9001

#logging:
#  level:
#    root: INFO
#    org.springframework.web: INFO
#    org.springframework.security: INFO
#    org.springframework.security.oauth2: INFO
##    org.springframework.boot.autoconfigure: DEBUG

logging:
  level:
    root: INFO
    org.springframework.web: TRACE
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.jdbc.core: debug

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://116.63.69.59:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: ciglink2020!@#
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl