server:
  port: 30001
spring:
  application:
    name: gateway-resource

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://116.63.69.59:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
#    username: root
#    password: ciglink2020!@#


  security:
    oauth2:
      resourceserver:
        jwt:
          # 不允许使用 127.0.0.1
          issuer-uri: http://localhost:9001
#            jwk-set-uri: http://localhost:9001/oauth2/jwks

logging:
  level:
    root: INFO
    org.springframework.web: TRACE
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.cloud.gateway: DEBUG

