server:
  port: 30000

spring:
  application:
    name: gateway

  security:
    oauth2:
      client:
        registration:
          messaging-client:
            provider: spring
            client-id: messaging-client
            client-secret: secret
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:30000/login/oauth2/code/messaging-client
            scope: openid,profile
            client-name: Spring
        provider:
          spring:
            authorization-uri: http://localhost:9001/oauth2/authorize
#            authorization-uri: http://localhost:9001/oauth2/consent
            token-uri: http://localhost:9001/oauth2/token
            jwk-set-uri: http://localhost:9001/oauth2/jwks
            issuer-uri: http://localhost:9001

  cloud:
    gateway:
      routes:
        - id: gateway-resource
          uri: http://127.0.0.1:30001
          predicates:
            - Path=/resource/api/**
          filters:
            #- StripPrefix=1
            - TokenRelay

logging:
  level:
    root: INFO
    org.springframework.web: TRACE
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.jdbc.core: debug