logging:
  level:
#    root: INFO
#    org.springframework.web: TRACE
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
#    org.springframework.boot.autoconfigure: DEBUG
#    org.springframework.cloud.gateway: DEBUG
#    org.springframework.jdbc.core: debug
